import { GoogleSpreadsheet } from "google-spreadsheet";

// @Injectable()
export class SheetsService {
  async getSheetValue(): Promise<string> {
    const sheetId = "123";

    const doc = new GoogleSpreadsheet(sheetId);
    await doc.useServiceAccountAuth({
      // env var values are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
      private_key: process.env.GOOGLE_PRIVATE_KEY,
    });
    await doc.loadInfo();

    return doc.title;
  }
}
